function Navbar() {
  return (
    <nav
      className="
        sticky
        top-0
        z-50
        flex
        items-center
        justify-between
        px-6
        md:px-10
        py-5
        bg-[#08121C]/80
        backdrop-blur-xl
        border-b
        border-white/10
        shadow-[0_8px_30px_rgb(0,0,0,0.3)]
      "
    >
      {/* Logo */}
      <h1
        className="
          text-2xl
          md:text-3xl
          font-extrabold
          tracking-widest
          cursor-pointer
          hover:scale-105
          transition-all
          duration-300
        "
      >
        RITWEEK
        <span className="text-orange-500">.</span>
      </h1>

      {/* Nav Links */}
      <ul className="hidden md:flex gap-10">

        <li>
          <a
            href="#home"
            className="
              relative
              text-gray-400
              hover:text-orange-500
              hover:-translate-y-1
              transition-all
              duration-300
              after:content-['']
              after:absolute
              after:left-0
              after:-bottom-1
              after:w-0
              after:h-[2px]
              after:bg-orange-500
              after:transition-all
              after:duration-300
              hover:after:w-full
            "
          >
            Home
          </a>
        </li>

        <li>
          <a
            href="#about"
            className="
              relative
              text-gray-400
              hover:text-orange-500
              hover:-translate-y-1
              transition-all
              duration-300
              after:content-['']
              after:absolute
              after:left-0
              after:-bottom-1
              after:w-0
              after:h-[2px]
              after:bg-orange-500
              after:transition-all
              after:duration-300
              hover:after:w-full
            "
          >
            About
          </a>
        </li>

        <li>
          <a
            href="#tech"
            className="
              relative
              text-gray-400
              hover:text-orange-500
              hover:-translate-y-1
              transition-all
              duration-300
              after:content-['']
              after:absolute
              after:left-0
              after:-bottom-1
              after:w-0
              after:h-[2px]
              after:bg-orange-500
              after:transition-all
              after:duration-300
              hover:after:w-full
            "
          >
            Tech Stack
          </a>
        </li>

        <li>
          <a
            href="#projects"
            className="
              relative
              text-gray-400
              hover:text-orange-500
              hover:-translate-y-1
              transition-all
              duration-300
              after:content-['']
              after:absolute
              after:left-0
              after:-bottom-1
              after:w-0
              after:h-[2px]
              after:bg-orange-500
              after:transition-all
              after:duration-300
              hover:after:w-full
            "
          >
            Projects
          </a>
        </li>

        <li>
          <a
            href="#certifications"
            className="
              relative
              text-gray-400
              hover:text-orange-500
              hover:-translate-y-1
              transition-all
              duration-300
              after:content-['']
              after:absolute
              after:left-0
              after:-bottom-1
              after:w-0
              after:h-[2px]
              after:bg-orange-500
              after:transition-all
              after:duration-300
              hover:after:w-full
            "
          >
            Certifications
          </a>
        </li>

        <li>
          <a
            href="#contact"
            className="
              relative
              text-gray-400
              hover:text-orange-500
              hover:-translate-y-1
              transition-all
              duration-300
              after:content-['']
              after:absolute
              after:left-0
              after:-bottom-1
              after:w-0
              after:h-[2px]
              after:bg-orange-500
              after:transition-all
              after:duration-300
              hover:after:w-full
            "
          >
            Contact
          </a>
        </li>

      </ul>

      {/* Resume Button */}
      <a
        href="/resume.pdf"
        download
        className="
          border
          border-orange-500
          px-5
          py-2
          rounded-xl
          text-orange-500
          font-medium
          hover:bg-orange-500
          hover:text-white
          hover:scale-105
          transition-all
          duration-300
          shadow-md
          hover:shadow-orange-500/30
        "
      >
        Resume
      </a>
    </nav>
  );
}

export default Navbar;